# Generated by Django 3.2.19 on 2023-08-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('institution_name', models.CharField(max_length=100)),
                ('type_of_course', models.CharField(max_length=200)),
                ('thematic_focus', models.TextField()),
                ('target_population', models.CharField(max_length=100)),
                ('scope', models.TextField()),
                ('objective_of_training', models.CharField(max_length=100)),
                ('target_audience', models.CharField(max_length=100)),
                ('traings_faculty', models.TextField()),
                ('teaching_mechanism', models.CharField(choices=[('Online', 'Online'), ('Face to Face', 'Face to Face'), ('Both', 'Both')], default='Online', max_length=20)),
                ('teaching_approach', models.CharField(max_length=100)),
                ('frequency_of_training', models.CharField(max_length=100)),
                ('funding_schemes', models.TextField()),
                ('sustainibility_factors', models.TextField()),
                ('key_challenges', models.TextField()),
                ('institution_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_database.country')),
            ],
        ),
    ]
